services:
  structurizr:
    image: structurizr/onpremises
    container_name: structurizr
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMIN_API_KEY=<CHANGE_ME>
    volumes:
      - ./_data:/usr/local/structurizr